web/router.ex
defmodule Wiki.Router do
  use Wiki.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Wiki.AuthenticationPlug
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Wiki do
    pipe_through :browser # Use the default browser stack

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    post "/logout", SessionController, :delete
    resources "/users", UserController
    resources "/", PageController do
      resources "/comments", CommentController, except: [:show, :edit, :update]
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", Wiki do
  #   pipe_through :api
  # end
end

web/models/comment.ex
defmodule Wiki.Comment do
  use Wiki.Web, :model

  schema "comments" do
    field :body, :string
    belongs_to :page, Wiki.Page

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:body])
    |> validate_required([:body])
  end
end

web/controllers/comment_controller.ex
defmodule Wiki.CommentController do
  use Wiki.Web, :controller

  alias Wiki.Comment

  def index(conn, _params) do
    page = load_page(conn)
    comments = Repo.all(assoc(page, :comments))
    render(conn, "index.html", comments: comments, page: page)
  end

  def new(conn, _params) do
    page = load_page(conn)
    changeset = Comment.changeset(%Comment{})
    render(conn, "new.html", changeset: changeset, page: page)
  end

  def create(conn, %{"comment" => comment_params}) do
    page = load_page(conn)
    changeset = 
      %Comment{page_id: page.id}
      |> Comment.changeset(comment_params)

    case Repo.insert(changeset) do
      {:ok, _comment} ->
        Wiki.Endpoint.broadcast! "page:#{page.id}", "comment_changed", %{}

        conn
        |> put_flash(:info, "Comment created successfully.")
        |> redirect(to: page_path(conn, :show, page))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset,page: page)
    end
  end

  def delete(conn, %{"id" => id}) do
    page = load_page(conn)
    comment = Repo.get!(assoc(page, :comments), id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(comment)

    Wiki.Endpoint.broadcast! "page:#{page.id}", "comment_changed", %{}

    conn
    |> put_flash(:info, "Comment deleted successfully.")
    |> redirect(to: page_path(conn, :show, page))
  end

  defp load_page(conn) do
    Wiki.Page
    |> Repo.get_by!(title: conn.params["page_id"])
    |> Repo.preload([:comments])
  end
end

web/views/comment_view.ex
defmodule Wiki.CommentView do
  use Wiki.Web, :view
end

web/templates/comment/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :body, class: "control-label" %>
    <%= textarea f, :body, class: "form-control" %>
    <%= error_tag f, :body %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/comment/index.html.eex
<h2>Listing comments</h2>

<table class="table">
  <thead>
    <tr>
      <th>Body</th>
      <th>Page</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for comment <- @comments do %>
    <tr>
      <td><%= comment.body %></td>
      <td><%= comment.page_id %></td>

      <td class="text-right">
        <%= link "Delete", to: page_comment_path(@conn, :delete, @page, comment), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New comment", to: page_comment_path(@conn, :new, @page) %>

web/templates/comment/new.html.eex
<h2>New comment</h2>

<%= render "form.html", changeset: @changeset,
                        action: page_comment_path(@conn, :create, @page) %>

<%= link "Back", to: page_comment_path(@conn, :index, @page) %>